---
version: '3.2'
services:
  server:
    build:
      context: ./server
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./server:/usr/src/app
    command: ["npm", "run", "debug"]
  client:
    build:
      context: ./client
    environment:
      NODE_ENV: development
      SERVER_URL: http://server:3000/primes/
    ports:
      - "9228:9229"
    volumes:
      - ./client:/usr/src/app
    command: ["npm", "run", "debug"]
