---
version: '3.2'
services:
  server:
    build:
      context: ./server
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
  client:
    depends_on:
      - server
    build:
      context: ./client
    environment:
      NODE_ENV: production
      SERVER_URL: http://server:3000/primes/
